import fs from 'fs';
import path from 'path';

function unescapeHTML(str) {
    return str
        .replace(/&gt;/g, '>')
        .replace(/&lt;/g, '<')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'");
}

function fixMermaid(filePath) {
    const fullPath = path.resolve(filePath);
    if (!fs.existsSync(fullPath)) {
        console.warn(`⚠️ File not found: ${fullPath}`);
        return;
    }

    let md = fs.readFileSync(fullPath, 'utf8');

    // Notice the \n\n added before and after the backticks
    // This forces GitHub to break out of the <p> and <dd> HTML tags!
    md = md.replace(/<pre><code class="language-mermaid">([\s\S]*?)<\/code><\/pre>/g, (match, innerContent) => {
        const decodedMermaid = unescapeHTML(innerContent.trim());
        return '\n\n```mermaid\n' + decodedMermaid + '\n```\n\n';
    });

    fs.writeFileSync(fullPath, md);
    console.log(`✅ Fixed Mermaid diagrams in ${filePath}`);
}

// Target the files generated by your npm scripts
fixMermaid('./docs/CLIENT_DOCS.md');
fixMermaid('./docs/SERVER_DOCS.md');